export const products = [
  {
    _id: "1",
    name: "asd as ds",
    category: "shirt",
    brand: "Nike",
    image: "/images/p1.jpg",
    description: "dd as dasdsasad as dsa dsa d as ds",
    price: 120,
    numberViews: 11,
    rating: 1,
    countInStock: 0,
  },
  {
    _id: "2",
    name: " cvb vbasd as ds",
    category: "shirt",
    brand: "Puma",
    image: "/images/p2.jpg",
    description: "cvut tybnx fgfs",
    price: 230,
    numberViews: 41,
    rating: 2,
    countInStock: 2,
  },
  {
    _id: "3",
    name: "bata tat ta",
    category: "shirt",
    brand: "Briony",
    image: "/images/p5.jpg",
    description: "gfnvb ibi ib fdf hsh  as ds",
    price: 180,
    numberViews: 64,
    rating: 2.5,
    countInStock: 12,
  },
  {
    _id: "4",
    name: "bata tat ta",
    category: "shirt",
    brand: "Briony",
    image: "/images/p5.jpg",
    description: "gfnvb ibi ib fdf hsh  as ds",
    price: 180,
    numberViews: 64,
    rating: 3,
    countInStock: 26,
  },
  {
    _id: "5",
    name: "bata tat ta",
    category: "shirt",
    brand: "Briony",
    image: "/images/p5.jpg",
    description: "gfnvb ibi ib fdf hsh  as ds",
    price: 180,
    numberViews: 64,
    rating: 4.5,
    countInStock: 5,
  },
];
